# -*- coding: utf-8 -*-
"""Heart_Failure_Clinical_Records.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BDNlc37aD2h0vZ2wOP61pdZ_fnzX5bR9

## The Objectives of this project:


1.   Check for missing values & make decision on how to handle them.
2.   What is the distribution of age among patients with and without death events?


1.   What is the gender distribution in the dataset? Does gender impact the likelihood of a death event?
2.   What are the average serum creatinine and serum sodium levels, & how do they differ between those who experience a death event & those who did not?


1.   Do patients with high blood pressure have a higher mortality rate?
2.   Is smoking associated with high chances of death in heart failure patients?


1.   What's the average time (follow-up period) for patients who died compared to those who survived?
"""

# import necessary packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""### Data Cleaning

### Read in file as dataframe
"""

df = pd.read_csv('/content/cleaned_clinical_records_dataset.csv')
df.head()

"""### Checking & Handling Missing Values"""

df.info()

# checking for missing values

df.isna().sum()

# convert float data type to int

df['age'] = df['age'].astype('int')
df['age']

"""### What is the distribution of age among patients with & without death events?"""

# filter out dead people and from that data we will look for their ages

death_events = df[df['DEATH_EVENT'] == 'Yes']
death_events['age'].describe()

"""###"""

# visualizing distribution through a histogram

ax = death_events['age'].plot(kind='hist', bins=20, color='orange', edgecolor='black')
ax.set_xlabel('Age')
ax.set_ylabel('Number of Deaths')  # counts per bin
ax.set_title('Age Distribution of Deceased Patients')
plt.grid(alpha=0.3)
plt.tight_layout(); plt.show()

# filter out dead people and from that data we will look for their ages

no_death_events = df[df['DEATH_EVENT'] == 'No']
no_death_events['age'].describe()

# visualizing distribution through a histogram

ax = no_death_events['age'].plot(kind='hist', bins=20, color='lightgreen', edgecolor='black')
ax.set_xlabel('Age')
ax.set_ylabel('No. of Alive People')  # counts per bin
ax.set_title('Age Distribution of Alive Patients')
plt.grid(alpha=0.3)
plt.tight_layout(); plt.show()

"""### What is the gender distribution in the dataset?"""

# percent of each gender in our dataset

# dataset uses 1=Male, 0=Female

map_sex = {'Yes': 'Male', 'No': 'Female', 1: 'Male', 0: 'Female', '1': 'Male', '0': 'Female'}

df['sex'] = df['sex'].map(map_sex).fillna(df['sex'])

# (Optional) make it a tidy categorical with a nice order
df['sex'] = pd.Categorical(df['sex'], categories=['Female', 'Male'], ordered=True)



out = (df['sex']
       .value_counts(normalize=True)
       .mul(100).round(1)
       .rename('percent')
       .to_frame()
       .reset_index()
       .rename(columns={'index': 'sex'}))
print(out)

# visualize distribution using pie chart

plt.figure(figsize=(5,5))
df['sex'].value_counts().plot(kind='pie', autopct='%.1f%%', ylabel='', colors = ['lightskyblue', 'pink'], title='Gender Distribution')
plt.axis('equal'); plt.show()

"""### Does Gender impact the likelihood of death event?"""

# group by gender & calculate death rate

# map death events to 1/0 (Yes=1, No=0)
df['DEATH_EVENT_NUM'] = df['DEATH_EVENT'].map({'Yes': 1, 'No': 0})

# group by gender and calculate death rate
gender_death_rate = (
    df.groupby('sex', observed=True)['DEATH_EVENT_NUM']
      .mean()
      .mul(100)     # convert to %
      .round(1)     # nicer display
)

print(gender_death_rate)

sns.countplot(x='sex', data=df, hue='DEATH_EVENT')

plt.title('Death Event Rate by Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.legend(title='Death Event')
plt.show()

# If p < 0.05 ; the diiference in death rates between genders is statistically significant; done to be sure

significant_value = 0.05


from scipy.stats import chi2_contingency        # Run the chi-square test of independence

tab = pd.crosstab(df['sex'], df['DEATH_EVENT'])  # counts table
chi2, p, dof, exp = chi2_contingency(tab)

print(tab)
print(f"p-value: {p:.3f}")  # p < 0.05 suggests a meaningful association

if p < significant_value:
    print("The difference in death rates between genders is statistically significant.")
else:
    print("There is no statistically significant difference in death rates between genders.")

"""### What are the average serum creatinine and serum sodium levels, & how do they differ between those who experience a death event & those who did not?

*  serum creatinine: mesure of kidney function (higher = worse)
*  serum sodium: lower values indicate poor heart function


"""

# finding the average values for creatinine & serum level
df[['serum_creatinine', 'serum_sodium']].mean()

# grouping by event and finding the average values for creatinine & serum level

df.groupby('DEATH_EVENT')[['serum_creatinine', 'serum_sodium']].mean()

# Death Event by Serum Creatinine

sns.boxplot(x='DEATH_EVENT', y='serum_creatinine', data=df)
plt.title('Death Event by Serum Creatinine Levels')
plt.xlabel('Death Event')
plt.ylabel('Serum Creatinine')
plt.show()

# Death Event by Serum Creatinine

sns.boxplot(x='DEATH_EVENT', y='serum_sodium', data=df)
plt.title('Death Event by Serum Sodium Levels')
plt.xlabel('Death Event')
plt.ylabel('Serum Sodium')
plt.show()

"""### Do patients with high blood pressure have a higher mortality rate?


"""

# Create a Cross Tab & count death events by BP

bp_death_counts = pd.crosstab(df['high_blood_pressure'], df['DEATH_EVENT'], margins = True)   # pd.crosstab() creates a cross-tabulation table; term for a table of counts
bp_death_counts

df.groupby('DEATH_EVENT')['high_blood_pressure'].value_counts(normalize=True).mul(100).round(1)       # normalize=True makes value_counts return proportions (not raw counts)

significant_value = 0.05


from scipy.stats import chi2_contingency        # Run the chi-square test of independence

tab = pd.crosstab(df['DEATH_EVENT'], df['high_blood_pressure'])  # counts table
chi2, p, dof, exp = chi2_contingency(tab)

print(f"p-value: {p:.3f}")  # p < 0.05 suggests a meaningful association

if p < significant_value:
    print("There is statistically significant association.")
else:
    print("There is no statistically significant association.")

"""### Is smoking associated with high chances of death in heart failure patients?"""

smk_death_counts = pd.crosstab(df['smoking'], df['DEATH_EVENT'], margins = True)   # pd.crosstab() creates a cross-tabulation table; term for a table of counts
smk_death_counts

df.groupby('DEATH_EVENT')['smoking'].value_counts(normalize=True).mul(100).round(1)

significant_value = 0.05


from scipy.stats import chi2_contingency        # Run the chi-square test of independence

tab = pd.crosstab(df['DEATH_EVENT'], df['smoking'])  # counts table
chi2, p, dof, exp = chi2_contingency(tab)

print(f"p-value: {p:.3f}")  # p < 0.05 suggests a meaningful association

if p < significant_value:
    print("There is statistically significant association.")
else:
    print("There is no statistically significant association.")

"""### What's the average time (follow-up period) for patients who died compared to those who survived?"""

df.groupby('DEATH_EVENT')['time'].mean()

sns.boxplot(x='DEATH_EVENT', y='time', data=df)
plt.title('Follow-up Time by Survival Status')
plt.xlabel('Death Event')
plt.ylabel('Follow-up Time (Days)')
plt.show()

"""###"""